name: Run Sonarqube code coverage

on:
  push:
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.GREEN_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.GREEN_SONAR_HOST_URL }}