name: Run Sonarqube code coverage

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

permissions:
      pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 18.x

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache --frozen-lockfile

      - name: Run tests
        run: yarn test --coverage
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
