name: Deploy to Vercel

on:
    pull_request:
        branches:
            - development
            - master
    push:
        branches:
            - development
            - master

jobs:
    deploy:
        name: Code checks and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache --frozen-lockfile

            - name: Run tests
              run: yarn test:coverage

            - name: Run linter
              run: yarn lint

            - name: Run typescript
              run: npx tsc

            - name: Deploy
              uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
